apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: lukonin/nginx:1.3.23-custom
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11
          args:
            - '-nginx.scrape-uri=http://localhost/basic_status'
          ports:
            - containerPort: 9113